import { Eye } from "lucide-react";

export const AttendanceData = [
  {
    id: 1,
    studentName: "Hamdoon",
    date: "2025-10-06",
    course: "Introduction to React",
    status: "Present",
    action: <Eye />,
  },
  {
    id: 2,
    studentName: "Safwan",
    date: "2025-10-06",
    course: "Javascript Fundamentals",
    status: "Present",
    action: <Eye />,
  },
  {
    id: 3,
    studentName: "Ahmed",
    date: "2025-10-06",
    course: "React Fundamentals",
    status: "Absent",
    action: <Eye />,
  },
  {
    id: 4,
    studentName: "Ali",
    date: "2025-10-06",
    course: "React Fundamentals",
    status: "Present",
    action: <Eye />,
  },
  {
    id: 5,
    studentName: "Zain",
    date: "2025-10-06",
    course: "Javascript Fundamentals",
    status: "Present",
    action: <Eye />,
  },
  {
    id: 6,
    studentName: "Maryum",
    date: "2025-10-06",
    course: "Javascript Fundamentals",
    status: "Absent",
    action: <Eye />,
  },
  {
    id: 7,
    studentName: "Sikandar",
    date: "2025-10-06",
    course: "Javascript Fundamentals",
    status: "Present",
    action: <Eye />,
  },
  {
    id: 8,
    studentName: "Abid",
    date: "2025-10-06",
    course: "Javascript Fundamentals",
    status: "Present",
    action: <Eye />,
  },
  {
    id: 9,
    studentName: "Ghous",
    date: "2025-10-06",
    course: "React Fundamentals",
    status: "Present",
    action: <Eye />,
  },
  {
    id: 10,
    studentName: "Faisal",
    date: "2025-10-06",
    course: "React Fundamentals",
    status: "Present",
    action: <Eye />,
  },
];
